include('ui/fcmd_matbrow.lua')

// print('#fcmdu.title.material_browser', language.GetPhrase('#fcmdu.title.material_browser'))
// print('#fcmdu.submit', language.GetPhrase('#fcmdu.submit'))
// print('#fcmdu.last_page', language.GetPhrase('#fcmdu.last_page'))
// print('#fcmdu.next_page', language.GetPhrase('#fcmdu.next_page'))
// print('#fcmdu.copy', language.GetPhrase('#fcmdu.copy'))
// print('#fcmdu.apply', language.GetPhrase('#fcmdu.apply'))
// print('#fcmdu.title.addon', language.GetPhrase('#fcmdu.title.addon'))
// print('#fcmdu.title.game', language.GetPhrase('#fcmdu.title.game'))
// print('#fcmdu.browse', language.GetPhrase('#fcmdu.browse'))

// print('#fcmdu.title.sound_browser', language.GetPhrase('#fcmdu.title.sound_browser'))

// print('#fcmdu.create', language.GetPhrase('#fcmdu.create'))
// print('#fcmdu.apply', language.GetPhrase('#fcmdu.apply'))
// print('#fcmdu.copy', language.GetPhrase('#fcmdu.copy'))
// print('#fcmdu.copy_content', language.GetPhrase('#fcmdu.copy_content'))
// print('#fcmdu.edit', language.GetPhrase('#fcmdu.edit'))
// print('#fcmdu.delete', language.GetPhrase('#fcmdu.delete'))

// print('#fcmdu.title.editor', language.GetPhrase('#fcmdu.title.editor'))

// print('#fcmdm.err.fatal', language.GetPhrase('#fcmdm.err.fatal'))
// print('#fcmdm.err.hook_die', language.GetPhrase('#fcmdm.err.hook_die'))
// print('#fcmdm.help.use', language.GetPhrase('#fcmdm.help.use'))

// print('#fcmdu.menu.category', language.GetPhrase('#fcmdu.menu.category'))
// print('#fcmdu.menu.name', language.GetPhrase('#fcmdu.menu.name'))
// print('#fcmdu.wheel_size', language.GetPhrase('#fcmdu.wheel_size'))
// print('#fcmdu.expand_key', language.GetPhrase('#fcmdu.expand_key'))
// print('#fcmdu.call_key', language.GetPhrase('#fcmdu.call_key'))
// print('#fcmdu.break_key', language.GetPhrase('#fcmdu.break_key'))
// print('#fcmdu.wfile', language.GetPhrase('#fcmdu.wfile'))
// print('#fcmdu.editor', language.GetPhrase('#fcmdu.editor'))
// print('#fcmdu.add_hook', language.GetPhrase('#fcmdu.add_hook'))
// print('#fcmdu.notify', language.GetPhrase('#fcmdu.notify'))

// print('#fcmd.warn.query', language.GetPhrase('#fcmd.warn.query'))
// print('#fcmd.help.query_addon_info', language.GetPhrase('#fcmd.help.query_addon_info'))
// print('#fcmd.warn.download', language.GetPhrase('#fcmd.warn.download'))
// print('#fcmd.help.download_addon_pre', language.GetPhrase('#fcmd.help.download_addon_pre'))
// print('#fcmd.warn.quote', language.GetPhrase('#fcmd.warn.quote'))
// print('#fcmd.err.parse', language.GetPhrase('#fcmd.err.parse'))
// print('#fcmd.err.json_err', language.GetPhrase('#fcmd.err.json_err'))
// print('#fcmd.warn.parse', language.GetPhrase('#fcmd.warn.parse'))
// print('#fcmd.warn.loss_field', language.GetPhrase('#fcmd.warn.loss_field'))
// print('#fcmd.warn.invalid_element', language.GetPhrase('#fcmd.warn.invalid_element'))
// print('#fcmd.warn.invalid_idx', language.GetPhrase('#fcmd.warn.invalid_idx'))
// print('#fcmd.err.dumps', language.GetPhrase('#fcmd.err.dumps'))
// print('#fcmd.err.not_table', language.GetPhrase('#fcmd.err.not_table'))
// print('#fcmd.err.load', language.GetPhrase('#fcmd.err.load'))
// print('#fcmd.err.not_json_suffix', language.GetPhrase('#fcmd.err.not_json_suffix'))
// print('#fcmd.err.is_folder', language.GetPhrase('#fcmd.err.is_folder'))
// print('#fcmd.err.file_not_exist', language.GetPhrase('#fcmd.err.file_not_exist'))
// print('#fcmd.err.save', language.GetPhrase('#fcmd.err.save'))
// print('#fcmd.err.file_exist', language.GetPhrase('#fcmd.err.file_exist'))
// print('#fcmd.err.copy', language.GetPhrase('#fcmd.err.copy'))
